/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-02-21 14:21:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.signD.contest;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import signD.member.LogonDataBean;
import signD.member.LogonDBBean;
import java.util.List;
import java.text.SimpleDateFormat;

public final class designRequest1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("signD.member.LogonDataBean");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("signD.member.LogonDBBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("utf-8");
	String title = "step1";
	String id = (String) session.getAttribute("id");

	LogonDBBean Logon = LogonDBBean.getInstance();
	LogonDataBean member = Logon.getMember(id);

	if (id != null && member.getType().equals("의뢰인")) {

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/_layout/header.inc.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(title), request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../module/menubar.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"bgi2\">\r\n");
      out.write("\t<section class=\"jumbotron text-center img-cover\">\r\n");
      out.write("\t\t<div class=\"container py-4\">\r\n");
      out.write("\t\t\t<h1 class=\"jumbotron-heading jumbotitle\"><strong>디자인 공모하기</strong></h1>\r\n");
      out.write("\t\t\t<p class=\"lead\"><strong>공모할 디자인의 종류를 선택하세요.</strong></p>\r\n");
      out.write("\t\t\t<div class=\"pt-3\">\r\n");
      out.write("\t\t\t\t<div class=\"row bs2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-3 dan\">1단계</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-3 nodan\">2단계</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-3 nodan\">3단계</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-3 nodan\">4단계</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"prog\"><div class=\"progress-bar\" style=\"width: 25%; background-color: tomato;\"></div></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container footerbottom\">\r\n");
      out.write("\t<div class=\"w3-row-padding w3-center w3-margin-top\">\r\n");
      out.write("\t\t<div class=\"w3-quarter\">\r\n");
      out.write("\t\t\t<a class=\"w3-button paddingz\" href=\"designRequest2_logo.jsp?category=logo\">\r\n");
      out.write("\t\t\t\t<div class=\"w3-card w3-container\" style=\"min-height: 460px\">\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<h3>LOGO</h3>\r\n");
      out.write("\t\t\t\t\t<p>로고</p>\r\n");
      out.write("\t\t\t\t\t<img src=\"../module/images1/logogogo.png\" class=\"ilg\" style=\"width: 50%\">\r\n");
      out.write("\t\t\t\t\t<div style=\"text-align: left\">\r\n");
      out.write("\t\t\t\t\t\t<ol class=\"listnon\" style=\"padding-left: 10%;\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"paddingb\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../module/images1/tick.png\" style=\"width: 15px;\" class=\"marginr\">30만원 부터</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"paddingb\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../module/images1/tick.png\" style=\"width: 15px;\" class=\"marginr\">로고 디자인</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"paddingb\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../module/images1/tick.png\" style=\"width: 15px;\" class=\"marginr\">간판 디자인</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"paddingb\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../module/images1/tick.png\" style=\"width: 15px;\" class=\"marginr\">서식류 디자인</li>\r\n");
      out.write("\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"w3-quarter\">\r\n");
      out.write("\t\t\t<a class=\"w3-button paddingz\" href=\"designRequest2_package.jsp?category=package\">\r\n");
      out.write("\t\t\t\t<div class=\"w3-card w3-container\" style=\"min-height: 460px\">\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<h3>PACKAGE</h3>\r\n");
      out.write("\t\t\t\t\t<p>패키지</p>\r\n");
      out.write("\t\t\t\t\t<img src=\"../module/images/box.png\" class=\"ilg\" style=\"width: 50%\">\r\n");
      out.write("\t\t\t\t\t<div style=\"text-align: left\">\r\n");
      out.write("\t\t\t\t\t\t<ol class=\"listnon\" style=\"padding-left: 10%;\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"paddingb\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../module/images1/tick.png\" style=\"width: 15px;\" class=\"marginr\">50만원 부터</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"paddingb\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../module/images1/tick.png\" style=\"width: 15px;\" class=\"marginr\">패키지 디자인</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"paddingb\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../module/images1/tick.png\" style=\"width: 15px;\" class=\"marginr\">라벨 디자인</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"paddingb\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../module/images1/tick.png\" style=\"width: 15px;\" class=\"marginr\">제품 디자인</li>\r\n");
      out.write("\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"w3-quarter\">\r\n");
      out.write("\t\t\t\t<a class=\"w3-button paddingz\" href=\"designRequest2_web.jsp?category=web\">\r\n");
      out.write("\t\t\t\t<div class=\"w3-card w3-container\" style=\"min-height: 460px\">\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<h3>WEB</h3>\r\n");
      out.write("\t\t\t\t\t<p>웹</p>\r\n");
      out.write("\t\t\t\t\t<img src=\"../module/images/website.png\" class=\"ilg\" style=\"width: 50%\"> <br>\r\n");
      out.write("\t\t\t\t\t<div style=\"text-align: left\">\r\n");
      out.write("\t\t\t\t\t\t<ol class=\"listnon\" style=\"padding-left: 10%;\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"paddingb\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../module/images1/tick.png\" style=\"width: 15px;\" class=\"marginr\">50만원 부터</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"paddingb\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../module/images1/tick.png\" style=\"width: 15px;\" class=\"marginr\">웹 사이트</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"paddingb\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../module/images1/tick.png\" style=\"width: 15px;\" class=\"marginr\">모바일 앱</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"paddingb\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../module/images1/tick.png\" style=\"width: 15px;\" class=\"marginr\">광고용 웹페이지</li>\r\n");
      out.write("\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"w3-quarter\">\r\n");
      out.write("\t\t\t<a class=\"w3-button paddingz\" href=\"designRequest2_other.jsp?category=other\">\r\n");
      out.write("\t\t\t\t<div class=\"w3-card w3-container\" style=\"min-height: 460px\">\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<h3>OTHER</h3>\r\n");
      out.write("\t\t\t\t\t<p>그 외</p>\r\n");
      out.write("\t\t\t\t\t<img src=\"../module/images/question.png\" class=\"ilg\" style=\"width: 50%\"> <br>\r\n");
      out.write("\t\t\t\t\t<div style=\"text-align: left\">\r\n");
      out.write("\t\t\t\t\t\t<ol class=\"listnon\" style=\"padding-left: 10%;\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"paddingb\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../module/images1/tick.png\" style=\"width: 15px;\" class=\"marginr\">30만원 부터</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"paddingb\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../module/images1/tick.png\" style=\"width: 15px;\" class=\"marginr\">일러스트</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"paddingb\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../module/images1/tick.png\" style=\"width: 15px;\" class=\"marginr\">캐릭터 디자인</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"paddingb\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../module/images1/tick.png\" style=\"width: 15px;\" class=\"marginr\">명함 디자인</li>\r\n");
      out.write("\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../module/bottom.jsp", out, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/_layout/footer.inc.jsp", out, false);
      out.write('\r');
      out.write('\n');

	} else {

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\talert('권한이 없습니다.');\r\n");
      out.write("\tdocument.location.href = \"../main.jsp\";\r\n");
      out.write("</script>\r\n");

	}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
